### ISSUE TITLE
hw

### ISSUE THREAD

**Issue by Lethe10137** [c7w/sast2022-pytorch-training#1]
https://github.com/Lethe10137/sast2022-pytorch-training/blob/master/README.md

**Comment by Lethe10137** [comment]
2021010826

**Comment by c7w** [comment]
Acknowleged. Wonderful Job ;)

1. 在上传代码时记得 ignore 掉 __pycache__，如果可能的话不要直接拖拽上传，使用  git push 上传就可以读取 .gitignore 文件的内容
2. 如果对这个领域感兴趣的话可以多看看相关视频进行后续学习 :)
