### ISSUE TITLE
homework submission

### ISSUE THREAD

**Issue by Chiyuru** [c7w/sast2022-pytorch-training#2]
（来自很菜的外系旁听人QAQ（

电脑的显卡是 A 卡，用不了 CUDA，所以发现 `main.py` 里一个地方有点问题：

```python
#main.py:
parser.add_argument("--device", type=int, default=0 if torch.cuda.is_available() else "cpu", help="Device number.")
#correct:
parser.add_argument("--device", type=int, default=0 if torch.cuda.is_available() else torch.device("cpu"), help="Device number.")
```

作业 Repo：https://github.com/Chiyuru/sast2022-pytorch-training ，学号 2021012561。

**Comment by c7w** [comment]
(1) 在 `dataset_landscape_generator.py`line 71-74，虽然 Python 有自动管理机制，但最好在写入文件后将文件关掉，或者使用 `with open() as f:` 装饰器在走出 with 的作用域后自动关掉文件。这是因为某些神奇的缓存机制可能会导致如果不及时关闭文件，你写入的内容可能不会及时写入到硬盘里...

(2) 确实可能用 CPU 训会存在你指出的这个问题，不过大部分情况下我们都是用 GPU 做训练的，所以在实际的生产环境中我们一般不处理这种情况，现在就当是这份代码是一个玩具，玩一玩就可以了qwq


Well Done! 如果对这个领域感兴趣的话欢迎继续深入了解 :)
